"""Host-facing catalog clients + offline fixtures.

This module is intentionally a thin API wrapper around `bittr_tess_vetter.platform.catalogs`.
Downstream applications should import from `bittr_tess_vetter.api.catalogs` rather
than deep-importing implementation modules.
"""

from bittr_tess_vetter.platform.catalogs.exofop_target_page import (  # noqa: F401
    ExoFOPTargetSummary,
    fetch_exofop_target_summary,
)
from bittr_tess_vetter.platform.catalogs.exofop_toi_table import (  # noqa: F401
    ExoFOPToiTable,
    fetch_exofop_toi_table,
)
from bittr_tess_vetter.platform.catalogs import (  # noqa: F401
    GAIA_TAP_ENDPOINT,
    RUWE_ELEVATED_THRESHOLD,
    SIMBAD_TAP_ENDPOINT,
    CatalogChecksumError,
    CatalogData,
    CatalogEntry,
    CatalogInstallError,
    CatalogNotFoundError,
    CatalogSnapshotStore,
    ContaminationRisk,
    CrossmatchError,
    CrossmatchReport,
    ExoplanetArchiveClient,
    ExoplanetArchiveError,
    GaiaAstrophysicalParams,
    GaiaClient,
    GaiaNeighbor,
    GaiaQueryError,
    GaiaQueryResult,
    GaiaSourceRecord,
    GaiaTAPError,
    InvalidSnapshotIdError,
    KnownObjectMatch,
    KnownPlanet,
    KnownPlanetsResult,
    NoCatalogsProvidedError,
    SimbadClient,
    SimbadIdentifiers,
    SimbadObjectType,
    SimbadQueryError,
    SimbadQueryResult,
    SimbadSpectralInfo,
    SimbadTAPError,
    SnapshotComponents,
    SnapshotNotFoundError,
    SpatialIndex,
    TAPQueryError,
    angular_separation_arcsec,
    assess_contamination,
    classify_object_type,
    compute_dilution_factor,
    crossmatch,
    determine_novelty_status,
    find_known_object_matches,
    generate_snapshot_id,
    get_exoplanet_archive_client,
    get_known_planets,
    parse_snapshot_id,
    parse_spectral_type,
    query_gaia_by_id_sync,
    query_gaia_by_position_sync,
    query_simbad_by_id_sync,
    query_simbad_by_position_sync,
    validate_snapshot_id,
)

__all__ = [
    # ExoFOP (TOI table + target pages)
    "ExoFOPToiTable",
    "fetch_exofop_toi_table",
    "ExoFOPTargetSummary",
    "fetch_exofop_target_summary",
    # Snapshot ID utilities
    "SnapshotComponents",
    "generate_snapshot_id",
    "parse_snapshot_id",
    "validate_snapshot_id",
    # Spatial indexing
    "SpatialIndex",
    # Catalog storage
    "CatalogChecksumError",
    "CatalogData",
    "CatalogInstallError",
    "CatalogNotFoundError",
    "CatalogSnapshotStore",
    # Crossmatch
    "ContaminationRisk",
    "CrossmatchError",
    "CrossmatchReport",
    "InvalidSnapshotIdError",
    "KnownObjectMatch",
    "NoCatalogsProvidedError",
    "SnapshotNotFoundError",
    "angular_separation_arcsec",
    "assess_contamination",
    "compute_dilution_factor",
    "crossmatch",
    "determine_novelty_status",
    "find_known_object_matches",
    "CatalogEntry",
    # Exoplanet Archive
    "ExoplanetArchiveClient",
    "ExoplanetArchiveError",
    "KnownPlanet",
    "KnownPlanetsResult",
    "TAPQueryError",
    "get_exoplanet_archive_client",
    "get_known_planets",
    # Gaia DR3
    "GAIA_TAP_ENDPOINT",
    "RUWE_ELEVATED_THRESHOLD",
    "GaiaAstrophysicalParams",
    "GaiaClient",
    "GaiaNeighbor",
    "GaiaQueryError",
    "GaiaQueryResult",
    "GaiaSourceRecord",
    "GaiaTAPError",
    "query_gaia_by_id_sync",
    "query_gaia_by_position_sync",
    # SIMBAD
    "SIMBAD_TAP_ENDPOINT",
    "SimbadClient",
    "SimbadIdentifiers",
    "SimbadObjectType",
    "SimbadQueryError",
    "SimbadQueryResult",
    "SimbadSpectralInfo",
    "SimbadTAPError",
    "classify_object_type",
    "parse_spectral_type",
    "query_simbad_by_id_sync",
    "query_simbad_by_position_sync",
]
