# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    # Install uv for faster dependency resolution
    pre_install:
      - pip install uv
    # Use uv to install the package with docs extras
    post_install:
      - uv pip install --system -e ".[docs]"

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Optionally build PDF and ePub
formats:
  - pdf

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
